[default]
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 0
block_timestamp = 0
cache = true
cache_path = 'cache'
evm_version = 'london'
extra_output = []
extra_output_files = []
ffi = false
force = false
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1024
fuzz_runs = 256
gas_limit = 80000000
gas_price = 0
gas_reports = ['*']
ignored_error_codes = [1878]
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = ['node_modules']
names = false
no_storage_caching = false
offline = false
optimizer = true
optimizer_runs = 200
out = 'out'
remappings = [
    '@boringcrypto/=node_modules/@boringcrypto/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@sushiswap/=node_modules/@sushiswap/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/@sushiswap/hardhat-framework/node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
sizes = false
src = 'contracts'
test = 'test'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
verbosity = 0
via_ir = false

[rpc_storage_caching]
chains = 'all'
endpoints = 'all'

